### ISSUE TITLE
Awa? Jetzt gibts ein Realease? Gestern hab ichs noch vom Source-Code bebuildet 😅

### ISSUE THREAD

**Issue by Sharknoon** [stefanDeveloper/scrum-retroboard#2]
Jetzt hab ich gestern das Scrum Retroboard komplett vom Source Code gebaut, weil ich neugierig war, Visual Studio Code installiert, Node-JS installiert und ewig gewartet bis yarn fertig war und als ich es heute endlich zum Laufen bekommen hatte, sehe ich, es gibt ein Release und ich hätte mir es ersparen können 😂🙈
Wir machen gerade ein ähnliches Projekt, eine Kommuniukations-App für Android, die speziell für Scrum Entwickler gedacht ist, daher mein Interesse.
Sieht echt mega aus dein Programm, bin schon gespannt wie es weiter geht 👍

#EigentlichKeinIssue 🤣

**Comment by stefanDeveloper** [comment]
Nice, das freut mich zu hören. Wenn du Vorschläge hast was man noch hinzufügen kann, dann bitte ein Issue aufmachen. Ansonsten würde es mich auch freuen, wenn ihr es für eure Retrospektive benutzen würdet 😊 

Für die nächsten Releases steht noch einiges an 😆
